Use native brotli when available and make iltorb & node-zopfli-es optional
Alorel/shrink-ray pull request #36
Opened 2019-04-27 01:51 UTC by zetlen

First off, thank you for maintaining this fork. Really appreciated.

## Purpose

Make `shrink-ray` more fault-tolerant, so it can install and run without fatal errors on more versions of Node and build environments.

### Ingredients

- Change hard dependencies on binary packages `iltorb` and `node-zopfli-es` to peer dependencies, so consuming apps can control their exact versions.
- Use native Brotli compression in NodeJS > 11.8 when available, and `iltorb` when not. When neither are available, fall back to gzip.
- Use `node-zopfli-es` when available, and fall back to gzip when not.
- Log warnings when fallbacks are in use.
- Update `node-zopfli-es` and `mocha` to comply with security audits.
- Add tests and `proxyquire` utility to simulate when modules are unavailable.

### Compatibility

Tested locally on Node:
- `v8.10.0`
- `v8.12.0`
- `v10.14.2`
- `v11.14.0`

2019-04-27 11:51 UTC, Alorel requested changes

2019-04-27 11:51 UTC, Alorel commented on brotli-compat.js
> +    console.warn(
I'd use `process.emitWarning` here

2019-04-27 11:51 UTC, Alorel commented on zopfli-compat.js
> +      console.warn(
And here

2019-04-27 11:53 UTC, Alorel commented
Hey, thanks for the PR. Looks good overall, just a couple of minor things. The Readme should also be updated with updated install instructions as the package now has peer dependencies.

2019-04-28 13:56 UTC, zetlen commented
Thanks for your prompt response, @Alorel ! I've switched to `process.emitWarning` and added README details.

2019-04-29 09:06 UTC, Alorel approved these changes

2019-04-29 09:08 UTC, Alorel commented
Great, thanks :slightly_smiling_face: I can't make edits to a forked project, so as soon as you resolve conflicts with master it'll be good to merge (it should only be a `node-zopfli-es` version change in package.json)

2019-04-29 12:56 UTC, zetlen commented
@Alorel I resolved the package.json conflicts last night and GitHub say there are no conflicts. Am I missing something?

2019-04-29 13:11 UTC, Alorel commented
Ah, the UI hadn't updated for some reason, it's fine now, cheers.

2019-04-29 13:15 UTC, merged

2019-04-29 13:22 UTC, Alorel commented
Published as v4.0.0 - thanks again for the contribution!